blob/blobs - porting over to hashicorp/go-azure-sdk's base layer
tombuildsstuff/giovanni pull request #85
Opened 2023-09-21 16:21 UTC by catriona-m

2023-11-08 13:45 UTC, tombuildsstuff requested changes
hey @catriona-m 

Thanks for this PR - apologies for the delayed review here.

I've taken a look through and left some comments inline, but on the whole this is looking pretty good - if we can fix those up this should otherwise be good to go 👍 

Thanks!

2023-11-08 14:08 UTC, catriona-m commented on storage/2020-08-04/blob/blobs/api.go
> +	CopyAndWait(ctx context.Context, containerName string, blobName string, input CopyInput, pollingInterval time.Duration) error
will it be ok to add this in a future pr with the file poller?

2023-11-08 14:35 UTC, tombuildsstuff commented on storage/2020-08-04/blob/blobs/api.go
> +	CopyAndWait(ctx context.Context, containerName string, blobName string, input CopyInput, pollingInterval time.Duration) error
Yep, sounds good 👍

2023-11-09 09:43 UTC, tombuildsstuff commented on storage/2020-08-04/blob/blobs/properties_get.go
> +				resp.IncrementalCopy = b
Looks like this one is still pending?

2023-11-09 11:23 UTC, catriona-m commented on storage/2020-08-04/blob/blobs/properties_get.go
> +				resp.IncrementalCopy = b
oops!! fixed now!

2023-11-10 14:35 UTC, tombuildsstuff approved these changes

2023-11-10 14:35 UTC, merged